/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pdf_tools_pdfviewer_Model_NativeObject */

#ifndef _Included_com_pdf_tools_pdfviewer_Model_NativeObject
#define _Included_com_pdf_tools_pdfviewer_Model_NativeObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    releaseTextFragment
 * Signature: (Lcom/pdf_tools/pdfviewer/Model/PdfTextFragment;)V
 */
JNIEXPORT void JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_releaseTextFragment
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    createObject
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_createObject
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    destroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_destroyObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getPageCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getPageCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getPageRect
 * Signature: (JI)Lcom/pdf_tools/pdfviewer/converter/geom/Rectangle/Double;
 */
JNIEXPORT jobject JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getPageRect
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getRotation
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getRotation
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    draw
 * Signature: (JIII[BIIIIIDDDD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_draw
  (JNIEnv *, jobject, jlong, jint, jint, jint, jbyteArray, jint, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getPageLayout
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getPageLayout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getOpenActionDestination
 * Signature: (J[I[Ljava/lang/Double;)I
 */
JNIEXPORT jint JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getOpenActionDestination
  (JNIEnv *, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getOutlineItems
 * Signature: (JI)[Lcom/pdf_tools/pdfviewer/Model/PdfOutlineItem;
 */
JNIEXPORT jobjectArray JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getOutlineItems
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getTextFragments
 * Signature: (JI)[Lcom/pdf_tools/pdfviewer/Model/PdfTextFragment;
 */
JNIEXPORT jobjectArray JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getTextFragments
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getAnnotationsOnPage
 * Signature: (JI)[Lcom/pdf_tools/pdfviewer/Annotations/PdfGenericAnnotation;
 */
JNIEXPORT jobjectArray JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getAnnotationsOnPage
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    updateAnnotation
 * Signature: (JLcom/pdf_tools/pdfviewer/Annotations/APdfAnnotation;)I
 */
JNIEXPORT jint JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_updateAnnotation
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    createAnnotation
 * Signature: (JLcom/pdf_tools/pdfviewer/Annotations/APdfAnnotation/TPdfAnnotationType;I[Ljava/lang/Double;)Lcom/pdf_tools/pdfviewer/Annotations/PdfGenericAnnotation;
 */
JNIEXPORT jobject JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_createAnnotation
  (JNIEnv *, jobject, jlong, jobject, jint, jobjectArray);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    deleteAnnotation
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_deleteAnnotation
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    saveAs
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_saveAs
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    setLicenseKey
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_setLicenseKey
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getLicenseIsValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getLicenseIsValid
  (JNIEnv *, jclass);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getProductVersion2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getProductVersion2
  (JNIEnv *, jclass);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     com_pdf_tools_pdfviewer_Model_NativeObject
 * Method:    getLastErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pdf_1tools_pdfviewer_Model_NativeObject_getLastErrorMessage
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_pdf_tools_pdfviewer_Model_NativeObject_TViewerError */

#ifndef _Included_com_pdf_tools_pdfviewer_Model_NativeObject_TViewerError
#define _Included_com_pdf_tools_pdfviewer_Model_NativeObject_TViewerError
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
