//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewerWPFSample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewerWPFSample.Properties.MainWindowRes", typeof(MainWindowRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotations.
        /// </summary>
        public static string annotations {
            get {
                return ResourceManager.GetString("annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only count number of  Strokes.
        /// </summary>
        public static string annotations_dummy {
            get {
                return ResourceManager.GetString("annotations_dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        public static string annotations_equals {
            get {
                return ResourceManager.GetString("annotations_equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormMapper.
        /// </summary>
        public static string annotations_formmapper {
            get {
                return ResourceManager.GetString("annotations_formmapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line width dependent on zoom.
        /// </summary>
        public static string annotations_linewithzoomdependent {
            get {
                return ResourceManager.GetString("annotations_linewithzoomdependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark annotations intersecting.
        /// </summary>
        public static string annotations_markonintersect {
            get {
                return ResourceManager.GetString("annotations_markonintersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not alter form of annotation.
        /// </summary>
        public static string annotations_nochange {
            get {
                return ResourceManager.GetString("annotations_nochange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter form of annotation to polyline.
        /// </summary>
        public static string annotations_polyline {
            get {
                return ResourceManager.GetString("annotations_polyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter form of annotation to rectangles.
        /// </summary>
        public static string annotations_rectangle {
            get {
                return ResourceManager.GetString("annotations_rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextRecognizer.
        /// </summary>
        public static string annotations_textrecognizer {
            get {
                return ResourceManager.GetString("annotations_textrecognizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textrecognition using WindowsInk.
        /// </summary>
        public static string annotations_windowsink {
            get {
                return ResourceManager.GetString("annotations_windowsink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border:.
        /// </summary>
        public static string border {
            get {
                return ResourceManager.GetString("border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug:.
        /// </summary>
        public static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Preferences that are embedded in the file.
        /// </summary>
        public static string debug_IgnoreEmbeddedPreferences {
            get {
                return ResourceManager.GetString("debug_IgnoreEmbeddedPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string document {
            get {
                return ResourceManager.GetString("document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double with title page.
        /// </summary>
        public static string double_title {
            get {
                return ResourceManager.GetString("double_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        public static string doublee {
            get {
                return ResourceManager.GetString("doublee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy Text Recognizer.
        /// </summary>
        public static string dummy_reco {
            get {
                return ResourceManager.GetString("dummy_reco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End search.
        /// </summary>
        public static string end_search {
            get {
                return ResourceManager.GetString("end_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First page.
        /// </summary>
        public static string first_page {
            get {
                return ResourceManager.GetString("first_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit:.
        /// </summary>
        public static string fit {
            get {
                return ResourceManager.GetString("fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit actual size.
        /// </summary>
        public static string fit_actual {
            get {
                return ResourceManager.GetString("fit_actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string fit_none {
            get {
                return ResourceManager.GetString("fit_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit page.
        /// </summary>
        public static string fit_page {
            get {
                return ResourceManager.GetString("fit_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit by width.
        /// </summary>
        public static string fit_width {
            get {
                return ResourceManager.GetString("fit_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last page.
        /// </summary>
        public static string last_page {
            get {
                return ResourceManager.GetString("last_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout:.
        /// </summary>
        public static string layout {
            get {
                return ResourceManager.GetString("layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find valid license key for this product..
        /// </summary>
        public static string license_key_invalid {
            get {
                return ResourceManager.GetString("license_key_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark a rectangular region.
        /// </summary>
        public static string mark {
            get {
                return ResourceManager.GetString("mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string next_page {
            get {
                return ResourceManager.GetString("next_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more matches found..
        /// </summary>
        public static string no_more_matches {
            get {
                return ResourceManager.GetString("no_more_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Change Reworker.
        /// </summary>
        public static string nochange_rework {
            get {
                return ResourceManager.GetString("nochange_rework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string open_file {
            get {
                return ResourceManager.GetString("open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page display:.
        /// </summary>
        public static string page_display {
            get {
                return ResourceManager.GetString("page_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows one scrollable Column of all pages.
        /// </summary>
        public static string PageLayoutOneColumn {
            get {
                return ResourceManager.GetString("PageLayoutOneColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows each page separately.
        /// </summary>
        public static string PageLayoutSinglePage {
            get {
                return ResourceManager.GetString("PageLayoutSinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows two columns of all pages.
        /// </summary>
        public static string PageLayoutTwoColumnLeft {
            get {
                return ResourceManager.GetString("PageLayoutTwoColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows two columns of all pages, with a separate cover page at the start.
        /// </summary>
        public static string PageLayoutTwoColumnRight {
            get {
                return ResourceManager.GetString("PageLayoutTwoColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a pair of pages separately.
        /// </summary>
        public static string PageLayoutTwoPageLeft {
            get {
                return ResourceManager.GetString("PageLayoutTwoPageLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a pair of pages separately, with a separate cover page at the start.
        /// </summary>
        public static string PageLayoutTwoPageRight {
            get {
                return ResourceManager.GetString("PageLayoutTwoPageRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauses and resumes drawing the layout.
        /// </summary>
        public static string pause_play_button {
            get {
                return ResourceManager.GetString("pause_play_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string previous_page {
            get {
                return ResourceManager.GetString("previous_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle Reworker.
        /// </summary>
        public static string rect_rework {
            get {
                return ResourceManager.GetString("rect_rework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string resolution {
            get {
                return ResourceManager.GetString("resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate right by 90°.
        /// </summary>
        public static string rotate_right {
            get {
                return ResourceManager.GetString("rotate_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation:.
        /// </summary>
        public static string rotation {
            get {
                return ResourceManager.GetString("rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        public static string search_match_case {
            get {
                return ResourceManager.GetString("search_match_case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found.
        /// </summary>
        public static string search_no_match {
            get {
                return ResourceManager.GetString("search_no_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search previous (not implemented).
        /// </summary>
        public static string search_previous {
            get {
                return ResourceManager.GetString("search_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use regular expressions.
        /// </summary>
        public static string search_regex {
            get {
                return ResourceManager.GetString("search_regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap around.
        /// </summary>
        public static string search_wrap {
            get {
                return ResourceManager.GetString("search_wrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border on/off.
        /// </summary>
        public static string shadow_on_off {
            get {
                return ResourceManager.GetString("shadow_on_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string single {
            get {
                return ResourceManager.GetString("single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be found..
        /// </summary>
        public static string text_not_found {
            get {
                return ResourceManager.GetString("text_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select text.
        /// </summary>
        public static string textSelection {
            get {
                return ResourceManager.GetString("textSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string undefined {
            get {
                return ResourceManager.GetString("undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Unit:.
        /// </summary>
        public static string userunit {
            get {
                return ResourceManager.GetString("userunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Outlines.
        /// </summary>
        public static string view_outlines {
            get {
                return ResourceManager.GetString("view_outlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Page Thumbnails.
        /// </summary>
        public static string view_page_list {
            get {
                return ResourceManager.GetString("view_page_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-Heights(TM) WPF PDF Viewer - DEMO.
        /// </summary>
        public static string window_title {
            get {
                return ResourceManager.GetString("window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Ink Text Recognizer.
        /// </summary>
        public static string windows_ink {
            get {
                return ResourceManager.GetString("windows_ink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        public static string zoom {
            get {
                return ResourceManager.GetString("zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string zoom_in {
            get {
                return ResourceManager.GetString("zoom_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change mouse to be used for zooming.
        /// </summary>
        public static string zoom_mode {
            get {
                return ResourceManager.GetString("zoom_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string zoom_out {
            get {
                return ResourceManager.GetString("zoom_out", resourceCulture);
            }
        }
    }
}
